# Generated by Django 3.1.7 on 2021-03-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydiary', '0002_auto_20210331_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='rate',
            field=models.IntegerField(),
        ),
    ]
